# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, tests ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on:  ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-10.15]
        python-version: [3.7,]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install .[test]
    - name: Import Tests
      run: |
        cd `mktemp -d`
        python -c "from midtools import dataset"
        python -c "from midtools import azimuthal_integration"
        python -c "from midtools import correlate"
        #    - name: Test with pytest
        #      run: |
        #        pytest

#     - name: Test with pytest
#       run: |
#         pytest
